spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/vertical-logistics
    username: vertical-logistics
    password: vertical-logistics123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
